services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $yamlIndent: '%aeliot_trans_maintain.yaml.indent%'

    Aeliot\Bundle\TransMaintain\Command\:
        resource: '../../Command/*'

    Aeliot\Bundle\TransMaintain\Service\:
        resource: '../../Service/*'
        exclude: '../../Service/{Translator.php,Yaml/TransformationConveyor.php,Yaml/KeyRegister.php}'

    Aeliot\Bundle\TransMaintain\Service\Yaml\KeyRegister:
        arguments:
            $dirs: [ ]
            $position: '%aeliot_trans_maintain.insert_missed_keys%'

    Aeliot\Bundle\TransMaintain\Service\Yaml\TransformationConveyor:
        arguments:
            $transformers:
                - '@Aeliot\Bundle\TransMaintain\Service\Yaml\Transformer\KeysCleaner'
                - '@Aeliot\Bundle\TransMaintain\Service\Yaml\Transformer\KeysTransformer'
                - '@Aeliot\Bundle\TransMaintain\Service\Yaml\Transformer\KeysSorter'
