services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $valueInvalidPattern: '%aeliot_trans_maintain.linter.value.invalid_pattern%'
            $yamlKeyPattern: '%aeliot_trans_maintain.yaml.key_pattern%'
            $yamlIndent: '%aeliot_trans_maintain.yaml.indent%'

    Aeliot\Bundle\TransMaintain\Command\:
        resource: '../../Command/*'

    Aeliot\Bundle\TransMaintain\Service\DirectoryProvider:
        arguments:
            $defaultPath: '%translator.default_path%'
            $dirs: [ ]

    Aeliot\Bundle\TransMaintain\Service\Yaml\:
        resource: '../../Service/Yaml/*'
        exclude: '../../Service/Yaml/{Inserter,Linter,KeyRegister.php,LinterRegistry.php,TransformationConveyor.php}'

    Aeliot\Bundle\TransMaintain\Service\Yaml\KeyRegister:
        arguments:
            $inserters: !tagged 'aeliot_trans_maintain.yaml.inserter'
            $position: '%aeliot_trans_maintain.insert_missed_keys%'
            $separateDirectory: '%aeliot_trans_maintain.missed_keys.directory%'

    Aeliot\Bundle\TransMaintain\Service\Yaml\Inserter\:
        resource: '../../Service/Yaml/Inserter/*'
        tags: [ 'aeliot_trans_maintain.yaml.inserter' ]

    Aeliot\Bundle\TransMaintain\Service\Yaml\Linter\:
        resource: '../../Service/Yaml/Linter/*'
        tags: [ 'aeliot_trans_maintain.yaml.linter' ]

    Aeliot\Bundle\TransMaintain\Service\Yaml\LinterRegistry:
        arguments:
            $linters: !tagged 'aeliot_trans_maintain.yaml.linter'

    Aeliot\Bundle\TransMaintain\Service\Yaml\TransformationConveyor:
        arguments:
            $transformers:
                - '@Aeliot\Bundle\TransMaintain\Service\Yaml\Transformer\KeysCleaner'
                - '@Aeliot\Bundle\TransMaintain\Service\Yaml\Transformer\KeysTransformer'
                - '@Aeliot\Bundle\TransMaintain\Service\Yaml\Transformer\KeysSorter'

    Aeliot\Bundle\TransMaintain\Service\ApiTranslator\Facades\GoogleTranslateFacade:
        arguments:
            $model: '%aeliot_trans_maintain.translation_api.google.model%'
        tags: [ 'aeliot_trans_maintain.api_translator.facade' ]

    Aeliot\Bundle\TransMaintain\Service\ApiTranslator\FacadesRegistry:
        arguments:
            $facades: !tagged 'aeliot_trans_maintain.api_translator.facade'

    Aeliot\Bundle\TransMaintain\Service\ApiTranslator\LimitKeeper:
        arguments:
            $limits: '%aeliot_trans_maintain.translation_api.limits%'

    Aeliot\Bundle\TransMaintain\Service\ApiTranslator\LimitRepository:
        arguments:
            $path: '%aeliot_trans_maintain.translation_api.report_path%'

    Aeliot\Bundle\TransMaintain\Service\ApiTranslator\ServiceUniqueIdProvider:
        arguments:
            $keys: '%aeliot_trans_maintain.translation_api.keys%'

    Aeliot\Bundle\TransMaintain\Service\ApiTranslator\Translator: ~

    Aeliot\Bundle\TransMaintain\Service\LocalesDetector: ~
    Aeliot\Bundle\TransMaintain\Service\ReportBagConsoleRenderer: ~

    Google\Cloud\Translate\V2\TranslateClient:
        arguments:
            $config: '%aeliot_trans_maintain.translation_api.google.config%'
