version: '3.1'

services:
  tramaint-php:
    build:
      context: ..
      dockerfile: docker/.Dockerfile
      args:
        PHP_XDEBUG_PORT: ${PHP_XDEBUG_PORT:-9003}
    restart: on-failure
    ports:
      - 9003:9003
    volumes:
      - ../:/srv/app
